"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { appStore } from "@/redux/store";
import { Provider } from "react-redux";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
       
      <body className="min-h-full flex flex-col">

        <Provider store={appStore}>
          {children}
        </Provider>

       {/* <Providers>
         {children}
       </Providers> */}
        </body>
    </html>
  );
}
